// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_app_analytics = 'enable';
var aws_cognito_identity_pool_id = 'us-east-1:1a400c7d-9be4-41a2-9d05-cfca8bbcf6ed';
var aws_cognito_region = 'us-east-1';
var aws_mobile_analytics_app_id = '54228392d4294d6c9aad70640332ccf6';
var aws_mobile_analytics_app_region = 'us-east-1';
var aws_project_id = 'cbddb7a7-e39b-417d-80ef-e1343307ce3b';
var aws_project_name = 'highARglyphs';
var aws_project_region = 'us-east-1';
var aws_resource_name_prefix = 'higharglyphs-mobilehub-161283959';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
